import { makeStyles } from "@fluentui/react-components"
import type { GriffelStyle } from "@griffel/react"

export const useCustomProductStyles = makeStyles({
  container: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingTop: "20px",
    paddingBottom: "20px",
    paddingLeft: "40px",
    paddingRight: "40px",
    maxWidth: "100%",
    margin: "0",
  } as GriffelStyle,

  title: {
    fontSize: "24px",
    fontWeight: "600",
    color: "#0078d4",
    margin: "0",
    marginBottom: "12px",
    textAlign: "left",
    alignSelf: "flex-start",
    marginLeft: "-20px",
  },

  gridContainer: {
    borderTopWidth: "3px",
    borderRightWidth: "3px",
    borderBottomWidth: "3px",
    borderLeftWidth: "3px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "#8bc34a",
    borderRightColor: "#8bc34a",
    borderBottomColor: "#8bc34a",
    borderLeftColor: "#8bc34a",
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "white",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
    width: "100%",
    minWidth: "800px",
  },

  gridWrapper: {
    maxHeight: "45rem",
    overflow: "hidden",
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },

  // ===== FILA DE AJUSTES CON CHECKBOX =====
  adjustmentRow: {
    display: "grid",
    gridTemplateColumns: "minmax(70px, 8%) 1fr minmax(180px, 180px)",
    borderBottomWidth: "2px",
    borderBottomStyle: "solid",
    borderBottomColor: "#8bc34a",
    backgroundColor: "#f8f9fa",
    position: "sticky",
    top: "0",
    zIndex: 11,
  },

  adjustmentLeft: {
    borderRightWidth: "3px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    color: "#666",
    fontWeight: "600",
    backgroundColor: "#f8f9fa",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "4px",
    paddingRight: "4px",
  },

  adjustmentMiddle: {
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },

  adjustmentRight: {
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    color: "#666",
    fontWeight: "600",
    backgroundColor: "#f8f9fa",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "4px",
    paddingRight: "4px",
  },

  adjustmentInputsGrid: {
    display: "grid",
    gap: "0",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "4px",
    paddingRight: "4px",
    alignItems: "center",
    minWidth: "fit-content",
    width: "100%",
  },

  adjustmentInput: {
    minWidth: "60px",
    width: "80px",
    maxWidth: "120px",
    height: "32px",
    textAlign: "center",
    fontSize: "12px",
    borderTopWidth: "2px",
    borderRightWidth: "2px",
    borderBottomWidth: "2px",
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "#8bc34a",
    borderRightColor: "#8bc34a",
    borderBottomColor: "#8bc34a",
    borderLeftColor: "#8bc34a",
    backgroundColor: "white",
    borderRadius: "4px",
    fontWeight: "500",
    margin: "0 auto",
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    paddingLeft: "4px",
    paddingRight: "4px",
  },

  // ===== FILA DE HEADERS CON CHECKBOX =====
  headerRow: {
    display: "grid",
    gridTemplateColumns: "40px minmax(70px, 8%) 1fr minmax(180px, 180px)",
    backgroundColor: "#8bc34a",
    position: "sticky",
    top: "42px",
    zIndex: 10,
  },

  headerCheckbox: {
    borderRightWidth: "3px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "40px",
    minWidth: "40px",
    maxWidth: "40px",
    height: "40px",
    minHeight: "40px",
  },

  headerLeft: {
    borderRightWidth: "3px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "1px",
    paddingRight: "1px",
    fontSize: "13px",
    fontWeight: "700",
    color: "white",
    minHeight: "40px",
  },

  headerMiddle: {
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },

  headerRight: {
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#8bc34a",
    backgroundColor: "#8bc34a",
    display: "flex",
  },

  headerParamsGrid: {
    display: "grid",
    gap: "0",
    minWidth: "fit-content",
    width: "100%",
  },

  headerCell: {
    minWidth: "80px",
    width: "100%",
    maxWidth: "none",
    borderRightWidth: "2px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "4px",
    paddingRight: "4px",
    fontSize: "13px",
    fontWeight: "700",
    color: "white",
    minHeight: "40px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    position: "relative",
    "&:last-child": {
      borderRightWidth: "0",
    },
  },

  headerCellFixed: {
    borderRightWidth: "2px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "#8bc34a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "4px",
    paddingRight: "4px",
    fontSize: "13px",
    fontWeight: "700",
    color: "white",
    height: "40px",
    minHeight: "40px",
    minWidth: "90px",
    width: "90px",
    maxWidth: "90px",
    flex: "0 0 90px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    position: "relative",
    "&:last-child": {
      borderRightWidth: "0",
    },
  },

  // ===== FILA DE DATOS CON CHECKBOX =====
  dataRow: {
    display: "grid",
    gridTemplateColumns: "40px minmax(70px, 8%) 1fr minmax(180px, 180px)",
    overflow: "hidden",
  },

  dataCheckbox: {
    borderRightWidth: "3px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "white",
    width: "40px",
    minWidth: "40px",
    maxWidth: "40px",
  },

  dataLeft: {
    borderRightWidth: "3px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    backgroundColor: "white",
  },

  dataMiddle: {
    overflowX: "auto",
    overflowY: "auto",
    maxHeight: "400px",
    scrollbarWidth: "thin",
    scrollbarColor: "#8bc34a #f0f0f0",
    "&::-webkit-scrollbar": {
      height: "8px",
      width: "8px",
    },
    "&::-webkit-scrollbar-track": {
      backgroundColor: "#f0f0f0",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "#8bc34a",
      borderRadius: "4px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      backgroundColor: "#7cb342",
    },
  },

  dataRight: {
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#8bc34a",
    backgroundColor: "white",
  },

  dataCheckboxContent: {
    display: "flex",
    flexDirection: "column",
  },

  dataLeftContent: {
    display: "flex",
    flexDirection: "column",
  },

  dataMiddleContent: {
    display: "flex",
    flexDirection: "column",
    minWidth: "fit-content",
    width: "100%",
  },

  dataRightContent: {
    display: "flex",
    flexDirection: "column",
  },

  dataRowGridFixed: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 90px)",
    gap: "0",
    minHeight: "40px",
    height: "40px",
  },

  dataRowGrid: {
    display: "grid",
    gap: "0",
    minWidth: "fit-content",
    width: "100%",
    minHeight: "40px",
  },

  checkboxCell: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#8bc34a",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "40px",
    minHeight: "40px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "0",
  },

  dataCellLeft: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#8bc34a",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "1px",
    paddingRight: "1px",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: "500",
    height: "40px",
    minHeight: "40px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    position: "relative",
  },

  dataCell: {
    minWidth: "80px",
    width: "100%",
    maxWidth: "none",
    borderRightWidth: "2px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#8bc34a",
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "2px",
    paddingRight: "2px",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:last-child": {
      borderRightWidth: "0",
    },
  },

  dataCellFixed: {
    borderRightWidth: "2px",
    borderRightStyle: "solid",
    borderRightColor: "#8bc34a",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "#8bc34a",
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "2px",
    paddingRight: "2px",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "40px",
    minHeight: "40px",
    maxWidth: "90px",
    minWidth: "90px",
    width: "90px",
    flex: "0 0 90px",
    "&:last-child": {
      borderRightWidth: "0",
    },
  },

  dataInput: {
    width: "100%",
    height: "100%",
    textAlign: "center",
    fontSize: "13px",
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "0",
    borderLeftWidth: "0",
    backgroundColor: "transparent",
    fontWeight: "500",
  },

  tooltip: {
    position: "absolute",
    bottom: "100%",
    left: "50%",
    transform: "translateX(-50%)",
    marginBottom: "8px",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: "#323130",
    color: "white",
    fontSize: "12px",
    borderRadius: "4px",
    whiteSpace: "nowrap",
    zIndex: 30,
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
    "&::after": {
      content: '""',
      position: "absolute",
      top: "100%",
      left: "50%",
      transform: "translateX(-50%)",
      borderTopWidth: "4px",
      borderRightWidth: "4px",
      borderBottomWidth: "4px",
      borderLeftWidth: "4px",
      borderTopStyle: "solid",
      borderRightStyle: "solid",
      borderBottomStyle: "solid",
      borderLeftStyle: "solid",
      borderTopColor: "#323130",
      borderRightColor: "transparent",
      borderBottomColor: "transparent",
      borderLeftColor: "transparent",
    },
  },

  controlsContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    paddingTop: "16px",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "0",
    backgroundColor: "transparent",
    borderRadius: "0",
    marginTop: "16px",
    width: "100%",
    boxShadow: "none",
  },

  controlsLeft: {
    display: "flex",
    gap: "24px",
    alignItems: "center",
    flex: "1",
  },

  controlGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },

  controlLabel: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#323130",
  },

  controlInputContainer: {
    display: "flex",
    alignItems: "center",
    gap: "0",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "#d1d1d1",
    borderRightColor: "#d1d1d1",
    borderBottomColor: "#d1d1d1",
    borderLeftColor: "#d1d1d1",
    borderRadius: "4px",
    backgroundColor: "white",
    overflow: "hidden",
  },

  controlInput: {
    width: "60px",
    height: "32px",
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "0",
    borderLeftWidth: "0",
    textAlign: "center",
    fontSize: "14px",
    fontWeight: "500",
    backgroundColor: "white",
    "&:focus": {
      outline: "none",
    },
  },

  incrementButton: {
    width: "32px",
    height: "32px",
    minWidth: "32px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "0",
    backgroundColor: "#f8f9fa",
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "0",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: "#d1d1d1",
    color: "#0078d4",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "#e9ecef",
    },
    "&:disabled": {
      color: "#a19f9d",
      cursor: "not-allowed",
    },
    "&:first-child": {
      borderLeftWidth: "0",
      borderRightWidth: "1px",
      borderRightStyle: "solid",
      borderRightColor: "#d1d1d1",
    },
  },

  buttonsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    alignItems: "center",
    flexShrink: 0,
    marginLeft: "auto",
  },

  outlineButton: {
    height: "36px",
    fontSize: "14px",
    fontWeight: "500",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "20px",
    paddingRight: "20px",
    backgroundColor: "white",
    borderTopWidth: "2px",
    borderRightWidth: "2px",
    borderBottomWidth: "2px",
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "#d1d1d1",
    borderRightColor: "#d1d1d1",
    borderBottomColor: "#d1d1d1",
    borderLeftColor: "#d1d1d1",
    color: "#323130",
    borderRadius: "6px",
    minWidth: "200px",
    "&:hover": {
      backgroundColor: "#f3f2f1",
      borderTopColor: "#c8c6c4",
      borderRightColor: "#c8c6c4",
      borderBottomColor: "#c8c6c4",
      borderLeftColor: "#c8c6c4",
    },
    "&:disabled": {
      backgroundColor: "#f3f2f1",
      borderTopColor: "#edebe9",
      borderRightColor: "#edebe9",
      borderBottomColor: "#edebe9",
      borderLeftColor: "#edebe9",
      color: "#a19f9d",
    },
  },

  primaryButton: {
    height: "44px",
    fontSize: "16px",
    fontWeight: "600",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "24px",
    paddingRight: "24px",
    backgroundColor: "#0078d4",
    borderTopWidth: "2px",
    borderRightWidth: "2px",
    borderBottomWidth: "2px",
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "#0078d4",
    borderRightColor: "#0078d4",
    borderBottomColor: "#0078d4",
    borderLeftColor: "#0078d4",
    color: "white",
    borderRadius: "6px",
    minWidth: "220px",
    marginTop: "8px",
    "&:hover": {
      backgroundColor: "#106ebe",
      borderTopColor: "#106ebe",
      borderRightColor: "#106ebe",
      borderBottomColor: "#106ebe",
      borderLeftColor: "#106ebe",
    },
  },
})
