import {
  SettingsRegular,
  BuildingRegular,
  ClipboardTaskRegular,
  ArchiveSettings24Filled,
  DataLine24Filled,
  DocumentTableSearch24Filled,
  AppsList24Filled,
  PuzzleCube24Filled,
  ClipboardTaskListRtl24Filled,
  WrenchSettings24Filled,
  Options24Color,
  BuildingFactory24Filled,
  Beaker24Filled,
  ClipboardDataBar24Filled,
  TableSettings24Filled,
  Settings24Filled,
  LayerDiagonal24Filled,
  Home24Filled,
  Search24Regular,
  Engine24Regular,
  Settings24Regular,
  SettingsChat24Filled,
  Planet24Regular,
  Box24Regular,
  History24Regular,
  ClockPause24Regular,
} from "@fluentui/react-icons";
import type { ComponentType } from "react";

export const ICON_MAP: Record<string, ComponentType<{ className?: string; fontSize?: number }>> = {
  'SettingsRegular': SettingsRegular,
  'BuildingRegular': BuildingRegular,
  'ClipboardTaskRegular': ClipboardTaskRegular,
  'DataLine24Filled': DataLine24Filled,
  'DocumentTableSearch24Filled': DocumentTableSearch24Filled,
  'WrenchSettings24Filled': WrenchSettings24Filled,
  'Options24Color': Options24Color,
  'ArchiveSettings24Filled': ArchiveSettings24Filled,
  'AppsList24Filled': AppsList24Filled,
  'PuzzleCube24Filled': PuzzleCube24Filled,
  'ClipboardTaskListRtl24Filled': ClipboardTaskListRtl24Filled,
  'BuildingFactory24Filled': BuildingFactory24Filled,
  'Beaker24Filled': Beaker24Filled,
  'ClipboardDataBar24Filled': ClipboardDataBar24Filled,
  'TableSettings24Filled': TableSettings24Filled,
  'Settings24Filled': Settings24Filled,
  'LayerDiagonal24Filled': LayerDiagonal24Filled,
  'Settings24Regular': Settings24Regular,
  'Planet24Regular': Planet24Regular,
  
  'Home': Home24Filled,
  'Search': Search24Regular,
  'ModelingView': Engine24Regular,
  'Settings': Settings24Regular,
  'SettingsApplications': SettingsChat24Filled,
  'Agriculture': Planet24Regular,
  'Package': Box24Regular,
  'Box': Box24Regular,
  'Box24Regular': Box24Regular,
  'History': History24Regular,
  'HistoryToggleOff': ClockPause24Regular,
};
