# Docs: https://github.com/Azure/webapps-deploy
# Deploy CSR Next.js app (export) to Azure App Service

name: Build and deploy Next.js SPA to Azure App Service - app-blending2-web-prod

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run export   #

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: ./out   # 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09E055E09BEB479ABAA730548C02FDEE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5FDE2D28E3E431285D5CB19D4EE9108 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAEA16754D0F4F6ABC6A3BC1EF678B93 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-blending2-web-prod'
          slot-name: 'Production'
          package: .
